pub(crate) mod activity;
pub(crate) mod browser;
pub(crate) mod connectivity;
pub(crate) mod dashboard;
pub(crate) mod diagnostics;
pub(crate) mod files;
pub(crate) mod scheduler;
pub(crate) mod terminal;
pub(crate) mod tunnel;
